### ISSUE TITLE
Misc Problems like storing not working, Stops during Leveling.

### ISSUE THREAD

**Issue by MarkusKress** [rommulaner/Anycubic_Vyper_MB_CE_6.2#37]
Hello.
I don't know if my Problems are related to the Version 6.2 or a defect of my Vyper. I saw these problems, probably only with this Version:
Storing like Z-Steppings are stored only after some tries. After going back to the main menu, I saw alwas settings stored, but after power off/on it was not stored. I did not saw this with the Version 6.1d.
During Leveling, the leveling stops after 1, 2 or 4 points (of 16). Mostly after I've doing a Home in Calibration Menue.

**Comment by rommulaner** [comment]
I saw the saving issue also on my vyper sometimes, I don't know why because when it says Settings Saved it does a M500. Maybe it connected to the recent flash process. But I t saves the Z-Offset that is changed during the print.
For the leveling you should ensure the order of homing and probe the Base Z-offset by clicking on the Home button at the calibration screen and start the ABL after that. You should also check if the cable is triggering the sensor during the Z movement, that will abort the ABL.

**Comment by MarkusKress** [comment]
I usually press Home (in Leveling Menu) before Leveling. But I tried it 4 times, and always  it stopped Leveling. So I tried without  Home and it works. That the reason I didn't Home before Leveling.
But I had an Idea: 
I have a Lamp on the Side of the printer and it can shine onto one of the Z-Homing Lightsensor. I think I have a different position of the Lamp after firmware upgrade. This might interrupted the leveling. It's a LED Lamp with cold color temperature. After a test without Light, the Leveling with Homing before works.

**Comment by rommulaner** [comment]
The light can only affect the homing process but not the leveling because the probing is done with the nozzle strain gauge and this works without light. But if the values are too far off because of a faulty homing, this can also lead to abort of the leveling. But then there also should be high values in the mesh as an indication.

**Comment by MarkusKress** [comment]
I have value like 2-3mm if I do not homing before Leveling. The Bed Mesh seems ok. Only max. 0,5 mm differences between Levels (-0,22 up to 0,30).

**Comment by rommulaner** [comment]
With active Fade Height you will get wrong part heights above the set height of 10mm if you don't set the base z-offset correctly.
